In [1]:
k = {
    "status": "success",
    "data": {
      "NSE:INFY": {
        "instrument_token": 408065,
        "timestamp": "2021-06-08 15:45:56",
        "last_trade_time": "2021-06-08 15:45:52",
        "last_price": 1412.95,
        "last_quantity": 5,
        "buy_quantity": 0,
        "sell_quantity": 5191,
        "volume": 7360198,
        "average_price": 1412.47,
        "oi": 0,
        "oi_day_high": 0,
        "oi_day_low": 0,
        "net_change": 0,
        "lower_circuit_limit": 1250.7,
        "upper_circuit_limit": 1528.6,
        "ohlc": {
          "open": 1396,
          "high": 1421.75,
          "low": 1395.55,
          "close": 1389.65
        },
        "depth": {
          "buy": [
            {
              "price": 0,
              "quantity": 0,
              "orders": 0
            },
            {
              "price": 0,
              "quantity": 0,
              "orders": 0
            },
            {
              "price": 0,
              "quantity": 0,
              "orders": 0
            },
            {
              "price": 0,
              "quantity": 0,
              "orders": 0
            },
            {
              "price": 0,
              "quantity": 0,
              "orders": 0
            }
          ],
          "sell": [
            {
              "price": 1412.95,
              "quantity": 5191,
              "orders": 13
            },
            {
              "price": 0,
              "quantity": 0,
              "orders": 0
            },
            {
              "price": 0,
              "quantity": 0,
              "orders": 0
            },
            {
              "price": 0,
              "quantity": 0,
              "orders": 0
            },
            {
              "price": 0,
              "quantity": 0,
              "orders": 0
            }
          ]
        }
      }
    }
  }

In [5]:
k['data']['NSE:INFY']['ohlc']['close']

1389.65

In [240]:
import requests

url = "https://api.kite.trade/quote"
headers = {
    "X-Kite-Version": "3",
    "Authorization": "token :"
}
params = {
    "i": ["NSE:INFY", "BSE:SENSEX", "NSE:NIFTY 50"]
}

response = requests.get(url, headers=headers, params=params)
data = response.json()

print(data)

{'status': 'success', 'data': {'BSE:SENSEX': {'instrument_token': 265, 'tradingsymbol': 'SENSEX', 'timestamp': '2024-04-02 17:05:27', 'last_price': 73903.91, 'net_change': -110.64, 'ohlc': {'open': 74022.3, 'high': 74099.78, 'low': 73743.77, 'close': 74014.55}}, 'NSE:INFY': {'instrument_token': 408065, 'timestamp': '2024-04-02 18:01:56', 'last_trade_time': '2024-04-02 15:59:56', 'last_price': 1482.85, 'last_quantity': 1, 'buy_quantity': 1018, 'sell_quantity': 0, 'volume': 7279400, 'average_price': 1484.83, 'oi': 0, 'oi_day_high': 0, 'oi_day_low': 0, 'net_change': 0, 'lower_circuit_limit': 1334.6, 'upper_circuit_limit': 1631.1, 'ohlc': {'open': 1484.85, 'high': 1493.15, 'low': 1480.85, 'close': 1495.45}, 'depth': {'buy': [{'price': 1482.85, 'quantity': 1018, 'orders': 71}, {'price': 0, 'quantity': 0, 'orders': 0}, {'price': 0, 'quantity': 0, 'orders': 0}, {'price': 0, 'quantity': 0, 'orders': 0}, {'price': 0, 'quantity': 0, 'orders': 0}], 'sell': [{'price': 0, 'quantity': 0, 'orders': 0}, {'price': 0, 'quantity': 0, 'orders': 0}, {'price': 0, 'quantity': 0, 'orders': 0}, {'price': 0, 'quantity': 0, 'orders': 0}, {'price': 0, 'quantity': 0, 'orders': 0}]}}, 'NSE:NIFTY 50': {'instrument_token': 256265, 'tradingsymbol': 'NIFTY 50', 'timestamp': '2024-04-02 18:08:17', 'last_price': 22453.3, 'net_change': -8.7, 'ohlc': {'open': 22458.8, 'high': 22497.6, 'low': 22388.15, 'close': 22462}}}}

In [241]:
data

{'status': 'success',
 'data': {'BSE:SENSEX': {'instrument_token': 265,
   'tradingsymbol': 'SENSEX',
   'timestamp': '2024-04-02 17:05:27',
   'last_price': 73903.91,
   'net_change': -110.64,
   'ohlc': {'open': 74022.3,
    'high': 74099.78,
    'low': 73743.77,
    'close': 74014.55}},
  'NSE:INFY': {'instrument_token': 408065,
   'timestamp': '2024-04-02 18:01:56',
   'last_trade_time': '2024-04-02 15:59:56',
   'last_price': 1482.85,
   'last_quantity': 1,
   'buy_quantity': 1018,
   'sell_quantity': 0,
   'volume': 7279400,
   'average_price': 1484.83,
   'oi': 0,
   'oi_day_high': 0,
   'oi_day_low': 0,
   'net_change': 0,
   'lower_circuit_limit': 1334.6,
   'upper_circuit_limit': 1631.1,
   'ohlc': {'open': 1484.85,
    'high': 1493.15,
    'low': 1480.85,
    'close': 1495.45},
   'depth': {'buy': [{'price': 1482.85, 'quantity': 1018, 'orders': 71},
     {'price': 0, 'quantity': 0, 'orders': 0},
     {'price': 0, 'quantity': 0, 'orders': 0},
     {'price': 0, 'quantity': 0, 'orders': 0},
     {'price': 0, 'quantity': 0, 'orders': 0}],
    'sell': [{'price': 0, 'quantity': 0, 'orders': 0},
     {'price': 0, 'quantity': 0, 'orders': 0},
     {'price': 0, 'quantity': 0, 'orders': 0},
     {'price': 0, 'quantity': 0, 'orders': 0},
     {'price': 0, 'quantity': 0, 'orders': 0}]}},
  'NSE:NIFTY 50': {'instrument_token': 256265,
   'tradingsymbol': 'NIFTY 50',
   'timestamp': '2024-04-02 18:08:17',
   'last_price': 22453.3,
   'net_change': -8.7,
   'ohlc': {'open': 22458.8,
    'high': 22497.6,
    'low': 22388.15,
    'close': 22462}}}}

In [10]:
data

{'status': 'success',
 'data': {'BSE:SENSEX': {'instrument_token': 265,
   'last_price': 72101.69,
   'ohlc': {'open': 72036.86,
    'high': 72402.67,
    'low': 71674.42,
    'close': 72012.05}},
  'NSE:INFY': {'instrument_token': 408065,
   'last_price': 1554.95,
   'ohlc': {'open': 1563, 'high': 1574.95, 'low': 1552.35, 'close': 1561.45}},
  'NSE:NIFTY 50': {'instrument_token': 256265,
   'last_price': 21839.1,
   'ohlc': {'open': 21843.9,
    'high': 21930.9,
    'low': 21710.2,
    'close': 21817.45}}}}

In [22]:
import time

In [212]:
import requests

url = "https://api.kite.trade/instruments"
headers = {
    "X-Kite-Version": "3",
    "Authorization": "token :"
}
params = {
    "i": ["NSE:INFY", "BSE:SENSEX", "NSE:NIFTY 50"]
}
s = time.time()
response = requests.get(url, headers=headers)
# data1 = response.json()
e = time.time()
# print(data1)

In [213]:
import json

In [214]:
import pandas as pd

In [215]:
from io import StringIO

In [216]:
csvStringIO = StringIO(response.text)

In [217]:
df = pd.read_csv(csvStringIO, sep=",")

In [221]:
df.name = df.name.fillna('')

In [236]:
df[(df.name.str.contains('RELIANCE')) & (df.expiry.isnull())]

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange
16715,137879812,538593,NCAPBUILAD,RELIANCE MUTUAL FUND- RELIANCE,0,NaN,0.0,0.01,1,EQ,BSE,BSE
16716,137880068,538594,NCAPBUILAG,RELIANCE MUTUAL FUND- RELIANCE,0,NaN,0.0,0.01,1,EQ,BSE,BSE
16717,137889796,538632,NCAPBUILBD,RELIANCE MUTUAL FUND- RELIANCE,0,NaN,0.0,0.01,1,EQ,BSE,BSE
16718,137890052,538633,NCAPBUILBG,RELIANCE MUTUAL FUND- RELIANCE,0,NaN,0.0,0.01,1,EQ,BSE,BSE
16719,137879300,538591,NCAPBULADD,RELIANCE MUTUAL FUND - RELIANC,0,NaN,0.0,0.01,1,EQ,BSE,BSE
16720,137879556,538592,NCAPBULADG,RELIANCE MUTUAL FUND- RELIANCE,0,NaN,0.0,0.01,1,EQ,BSE,BSE
16721,137889284,538630,NCAPBULBDD,RELIANCE MUTUAL FUND - RELIANC,0,NaN,0.0,0.01,1,EQ,BSE,BSE
16722,137889540,538631,NCAPBULBDG,RELIANCE MUTUAL FUND- RELIANCE,0,NaN,0.0,0.01,1,EQ,BSE,BSE
17519,128809476,503162,RELCHEMQ,RELIANCE CHEMOTEX INDUSTRIES L,0,NaN,0.0,0.05,1,EQ,BSE,BSE
17521,128083204,500325,RELIANCE,RELIANCE INDUSTRIES.,0,NaN,0.0,0.05,1,EQ,BSE,BSE
17525,128099844,500390,RELINFRA,RELIANCE INFRASTRUCTURE.,0,NaN,0.0,0.05,1,EQ,BSE,BSE
17591,134001924,523445,RIIL,RELIANCE INDUSTRIAL INFRASTRUC,0,NaN,0.0,0.05,1,EQ,BSE,BSE
82443,2470913,9652,RELCHEMQ,RELIANCE CHEMOTEX IND,0,NaN,0.0,0.05,1,EQ,NSE,NSE
82445,738561,2885,RELIANCE,RELIANCE INDUSTRIES,0,NaN,0.0,0.05,1,EQ,NSE,NSE
82447,141569,553,RELINFRA,RELIANCE INFRASTRUCTU,0,NaN,0.0,0.05,1,EQ,NSE,NSE
82457,5564673,21737,RHFL-BE,RELIANCE HOME FINANCE,0,NaN,0.0,0.05,1,EQ,NSE,NSE
82462,745473,2912,RIIL,RELIANCE INDUSTRIAL INFRA,0,NaN,0.0,0.05,1,EQ,NSE,NSE
82485,3906817,15261,RPOWER-BE,RELIANCE POWER.,0,NaN,0.0,0.05,1,EQ,NSE,NSE

In [218]:
df[df.tradingsymbol == 'RCOM']

Empty DataFrame
Columns: [instrument_token, exchange_token, tradingsymbol, name, last_price, expiry, strike, tick_size, lot_size, instrument_type, segment, exchange]
Index: []

In [30]:
df.groupby('exchange')['exchange'].count()

exchange
BCD       3792
BFO       4056
BSE      11451
CDS      11353
MCX       4571
NFO      41026
NSE       6183
NSEIX        1
Name: exchange, dtype: int64

In [31]:
nse_df = df[df.exchange == 'NSE']

In [111]:
for i, row in nse_df[~nse_df.name.isnull()].iterrows():
    if row['name'] is not None and 'VLEGOV' in row['tradingsymbol']:
        print(row['tradingsymbol'])

VLEGOV-BE

In [115]:
len([x.split('-')[0] for x in nse_df['tradingsymbol']])

6183

In [119]:
nse_df['pre_split'] = nse_df['tradingsymbol'].apply(lambda x: x.split('-')[0])

/var/folders/d4/cgyr_gnj7nn2wy_hq40gkq8c0000gq/T/ipykernel_99828/2035714057.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nse_df['pre_split'] = nse_df['tradingsymbol'].apply(lambda x: x.split('-')[0])

In [193]:
nse_df.groupby('segment')['segment'].count()

segment
INDICES      72
NSE        6111
Name: segment, dtype: int64

In [197]:
nse_df[nse_df.tradingsymbol == 'HDFCNIFBAN']

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange,pre_split,primary,unique_primary_count,num_symbols
80205,5742849,22433,HDFCNIFBAN,HDFCAMC - HDFCNIFBAN,0,NaN,0.0,0.01,1,EQ,NSE,NSE,HDFCNIFBAN,False,1,1

In [211]:
def calculate_annualized_growth_rate(growth_rate, days):
    """
    Calculate the annualized growth rate from a given growth rate over a certain number of days.

    :param growth_rate: The growth rate over the period (e.g., 1.25 for 25% growth)
    :param days: The number of days over which the growth rate was observed
    :return: The annualized growth rate as a decimal (e.g., 0.25 for 25%)
    """
    if days == 0:
        raise ValueError("Number of days cannot be zero")

    # Convert growth rate to a rate of change (e.g., 1.25 to 0.25)
    rate_of_change = growth_rate - 1

    # Calculate the annualized growth rate
    annualized_growth_rate = (1 + rate_of_change) ** (365 / days) - 1

    return annualized_growth_rate

# Example usage
growth_rate = 1.25  # 25% growth
days = 180
annualized_rate = calculate_annualized_growth_rate(growth_rate, days)
print(f"Annualized Growth Rate: {annualized_rate * 100:.2f}%")

Annualized Growth Rate: 57.22%

In [207]:
nse_df[nse_df.tradingsymbol.str.contains('NIFTY')]

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange,pre_split,primary,unique_primary_count,num_symbols
19324,260617,1018,NIFTY 100,NIFTY 100,0,NaN,0.0,0.00,0,EQ,INDICES,NSE,NIFTY 100,False,1,1
19325,264457,1033,NIFTY 200,NIFTY 200,0,NaN,0.0,0.00,0,EQ,INDICES,NSE,NIFTY 200,False,1,1
19326,256265,1001,NIFTY 50,NIFTY 50,0,NaN,0.0,0.00,0,EQ,INDICES,NSE,NIFTY 50,False,1,1
19327,268041,1047,NIFTY 500,NIFTY 500,0,NaN,0.0,0.00,0,EQ,INDICES,NSE,NIFTY 500,False,1,1
19328,265993,1039,NIFTY ALPHA 50,NIFTY ALPHA 50,0,NaN,0.0,0.00,0,EQ,INDICES,NSE,NIFTY ALPHA 50,False,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81292,5621505,21959,NIFTYBETF,BFAM - NIFTYBETF,0,NaN,0.0,0.01,1,EQ,NSE,NSE,NIFTYBETF,False,1,1
81293,1626369,6353,NIFTYETF,MIRAEAMC - MAN50ETF,0,NaN,0.0,0.01,1,EQ,NSE,NSE,NIFTYETF,False,1,1
81294,7565569,29553,NIFTYIETF,ICICI PRUD NIFTY ETF,0,NaN,0.0,0.01,1,EQ,NSE,NSE,NIFTYIETF,False,1,1
81295,2736641,10690,NIFTYQLITY,BIRLASLAMC - NIFTYQLITY,0,NaN,0.0,0.01,1,EQ,NSE,NSE,NIFTYQLITY,False,1,1
81563,4305665,16819,QNIFTY,QUANTUM NIFTY 50 ETF,0,NaN,0.0,0.01,1,EQ,NSE,NSE,QNIFTY,False,1,1

In [206]:
nse_df[nse_df.tradingsymbol.str.contains('NIFTY')].head(30)

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange,pre_split,primary,unique_primary_count,num_symbols
19324,260617,1018,NIFTY 100,NIFTY 100,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY 100,False,1,1
19325,264457,1033,NIFTY 200,NIFTY 200,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY 200,False,1,1
19326,256265,1001,NIFTY 50,NIFTY 50,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY 50,False,1,1
19327,268041,1047,NIFTY 500,NIFTY 500,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY 500,False,1,1
19328,265993,1039,NIFTY ALPHA 50,NIFTY ALPHA 50,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY ALPHA 50,False,1,1
19329,273673,1069,NIFTY ALPHALOWVOL,NIFTY ALPHALOWVOL,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY ALPHALOWVOL,False,1,1
19330,263433,1029,NIFTY AUTO,NIFTY AUTO,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY AUTO,False,1,1
19331,260105,1016,NIFTY BANK,NIFTY BANK,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY BANK,False,1,1
19332,257289,1005,NIFTY COMMODITIES,NIFTY COMMODITIES,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY COMMODITIES,False,1,1
19333,288777,1128,NIFTY CONSR DURBL,NIFTY CONSR DURBL,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY CONSR DURBL,False,1,1
19334,257545,1006,NIFTY CONSUMPTION,NIFTY CONSUMPTION,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY CONSUMPTION,False,1,1
19335,268297,1048,NIFTY CPSE,NIFTY CPSE,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY CPSE,False,1,1
19336,257033,1004,NIFTY DIV OPPS 50,NIFTY DIV OPPS 50,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY DIV OPPS 50,False,1,1
19337,261641,1022,NIFTY ENERGY,NIFTY ENERGY,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY ENERGY,False,1,1
19338,257801,1007,NIFTY FIN SERVICE,NIFTY FIN SERVICE,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY FIN SERVICE,False,1,1
19339,288265,1126,NIFTY FINSRV25 50,NIFTY FINSRV25 50,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY FINSRV25 50,False,1,1
19340,261897,1023,NIFTY FMCG,NIFTY FMCG,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY FMCG,False,1,1
19341,270345,1056,NIFTY GROWSECT 15,NIFTY GROWSECT 15,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GROWSECT 15,False,1,1
19342,269065,1051,NIFTY GS 10YR,NIFTY GS 10YR,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 10YR,False,1,1
19343,269321,1052,NIFTY GS 10YR CLN,NIFTY GS 10YR CLN,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 10YR CLN,False,1,1
19344,269577,1053,NIFTY GS 11 15YR,NIFTY GS 11 15YR,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 11 15YR,False,1,1
19345,269833,1054,NIFTY GS 15YRPLUS,NIFTY GS 15YRPLUS,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 15YRPLUS,False,1,1
19346,268553,1049,NIFTY GS 4 8YR,NIFTY GS 4 8YR,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 4 8YR,False,1,1
19347,268809,1050,NIFTY GS 8 13YR,NIFTY GS 8 13YR,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 8 13YR,False,1,1
19348,270089,1055,NIFTY GS COMPSITE,NIFTY GS COMPSITE,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS COMPSITE,False,1,1
19349,288521,1127,NIFTY HEALTHCARE,NIFTY HEALTHCARE,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY HEALTHCARE,False,1,1
19350,291337,1138,NIFTY IND DIGITAL,NIFTY IND DIGITAL,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY IND DIGITAL,False,1,1
19351,291081,1137,NIFTY INDIA MFG,NIFTY INDIA MFG,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY INDIA MFG,False,1,1
19352,261385,1021,NIFTY INFRA,NIFTY INFRA,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY INFRA,False,1,1
19353,259849,1015,NIFTY IT,NIFTY IT,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY IT,False,1,1

In [195]:
nse_df[nse_df.segment == 'INDICES'].head(30)

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange,pre_split,primary,unique_primary_count,num_symbols
19322,264713,1034,HANGSENG BEES-NAV,HANGSENG BEES-NAV,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,HANGSENG BEES,True,1,1
19323,264969,1035,INDIA VIX,INDIA VIX,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,INDIA VIX,False,1,1
19324,260617,1018,NIFTY 100,NIFTY 100,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY 100,False,1,1
19325,264457,1033,NIFTY 200,NIFTY 200,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY 200,False,1,1
19326,256265,1001,NIFTY 50,NIFTY 50,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY 50,False,1,1
19327,268041,1047,NIFTY 500,NIFTY 500,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY 500,False,1,1
19328,265993,1039,NIFTY ALPHA 50,NIFTY ALPHA 50,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY ALPHA 50,False,1,1
19329,273673,1069,NIFTY ALPHALOWVOL,NIFTY ALPHALOWVOL,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY ALPHALOWVOL,False,1,1
19330,263433,1029,NIFTY AUTO,NIFTY AUTO,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY AUTO,False,1,1
19331,260105,1016,NIFTY BANK,NIFTY BANK,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY BANK,False,1,1
19332,257289,1005,NIFTY COMMODITIES,NIFTY COMMODITIES,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY COMMODITIES,False,1,1
19333,288777,1128,NIFTY CONSR DURBL,NIFTY CONSR DURBL,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY CONSR DURBL,False,1,1
19334,257545,1006,NIFTY CONSUMPTION,NIFTY CONSUMPTION,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY CONSUMPTION,False,1,1
19335,268297,1048,NIFTY CPSE,NIFTY CPSE,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY CPSE,False,1,1
19336,257033,1004,NIFTY DIV OPPS 50,NIFTY DIV OPPS 50,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY DIV OPPS 50,False,1,1
19337,261641,1022,NIFTY ENERGY,NIFTY ENERGY,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY ENERGY,False,1,1
19338,257801,1007,NIFTY FIN SERVICE,NIFTY FIN SERVICE,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY FIN SERVICE,False,1,1
19339,288265,1126,NIFTY FINSRV25 50,NIFTY FINSRV25 50,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY FINSRV25 50,False,1,1
19340,261897,1023,NIFTY FMCG,NIFTY FMCG,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY FMCG,False,1,1
19341,270345,1056,NIFTY GROWSECT 15,NIFTY GROWSECT 15,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GROWSECT 15,False,1,1
19342,269065,1051,NIFTY GS 10YR,NIFTY GS 10YR,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 10YR,False,1,1
19343,269321,1052,NIFTY GS 10YR CLN,NIFTY GS 10YR CLN,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 10YR CLN,False,1,1
19344,269577,1053,NIFTY GS 11 15YR,NIFTY GS 11 15YR,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 11 15YR,False,1,1
19345,269833,1054,NIFTY GS 15YRPLUS,NIFTY GS 15YRPLUS,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 15YRPLUS,False,1,1
19346,268553,1049,NIFTY GS 4 8YR,NIFTY GS 4 8YR,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 4 8YR,False,1,1
19347,268809,1050,NIFTY GS 8 13YR,NIFTY GS 8 13YR,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS 8 13YR,False,1,1
19348,270089,1055,NIFTY GS COMPSITE,NIFTY GS COMPSITE,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY GS COMPSITE,False,1,1
19349,288521,1127,NIFTY HEALTHCARE,NIFTY HEALTHCARE,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY HEALTHCARE,False,1,1
19350,291337,1138,NIFTY IND DIGITAL,NIFTY IND DIGITAL,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY IND DIGITAL,False,1,1
19351,291081,1137,NIFTY INDIA MFG,NIFTY INDIA MFG,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,NIFTY INDIA MFG,False,1,1

In [191]:
nse_df[nse_df.tradingsymbol.str.contains('NIFTY')]

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange,pre_split,primary,unique_primary_count,num_symbols
19324,260617,1018,NIFTY 100,NIFTY 100,0,NaN,0.0,0.00,0,EQ,INDICES,NSE,NIFTY 100,False,1,1
19325,264457,1033,NIFTY 200,NIFTY 200,0,NaN,0.0,0.00,0,EQ,INDICES,NSE,NIFTY 200,False,1,1
19326,256265,1001,NIFTY 50,NIFTY 50,0,NaN,0.0,0.00,0,EQ,INDICES,NSE,NIFTY 50,False,1,1
19327,268041,1047,NIFTY 500,NIFTY 500,0,NaN,0.0,0.00,0,EQ,INDICES,NSE,NIFTY 500,False,1,1
19328,265993,1039,NIFTY ALPHA 50,NIFTY ALPHA 50,0,NaN,0.0,0.00,0,EQ,INDICES,NSE,NIFTY ALPHA 50,False,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81292,5621505,21959,NIFTYBETF,BFAM - NIFTYBETF,0,NaN,0.0,0.01,1,EQ,NSE,NSE,NIFTYBETF,False,1,1
81293,1626369,6353,NIFTYETF,MIRAEAMC - MAN50ETF,0,NaN,0.0,0.01,1,EQ,NSE,NSE,NIFTYETF,False,1,1
81294,7565569,29553,NIFTYIETF,ICICI PRUD NIFTY ETF,0,NaN,0.0,0.01,1,EQ,NSE,NSE,NIFTYIETF,False,1,1
81295,2736641,10690,NIFTYQLITY,BIRLASLAMC - NIFTYQLITY,0,NaN,0.0,0.01,1,EQ,NSE,NSE,NIFTYQLITY,False,1,1
81563,4305665,16819,QNIFTY,QUANTUM NIFTY 50 ETF,0,NaN,0.0,0.01,1,EQ,NSE,NSE,QNIFTY,False,1,1

In [138]:
nse_df[nse_df.tradingsymbol.str.contains('-')]

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange,pre_split
19322,264713,1034,HANGSENG BEES-NAV,HANGSENG BEES-NAV,0,NaN,0.0,0.00,0,EQ,INDICES,NSE,HANGSENG BEES
76322,1749249,6833,1018GS2026-GS,NaN,0,NaN,0.0,0.01,1,EQ,NSE,NSE,1018GS2026
76323,5762817,22511,182D010824-TB,NaN,0,NaN,0.0,0.01,100,EQ,NSE,NSE,182D010824
76324,5056001,19750,182D020524-TB,NaN,0,NaN,0.0,0.01,100,EQ,NSE,NSE,182D020524
76325,4914433,19197,182D040424-TB,NaN,0,NaN,0.0,0.01,100,EQ,NSE,NSE,182D040424
...,...,...,...,...,...,...,...,...,...,...,...,...,...
82411,4618241,18040,YUDIZ-SM,YUDIZ SOLUTIONS,0,NaN,0.0,0.05,800,EQ,NSE,NSE,YUDIZ
82414,4548097,17766,ZEAL-SM,ZEAL GLOBAL SERVICES,0,NaN,0.0,0.05,600,EQ,NSE,NSE,ZEAL
82416,5339137,20856,ZEELEARN-BE,ZEE LEARN,0,NaN,0.0,0.05,1,EQ,NSE,NSE,ZEELEARN
82418,5837569,22803,ZENITHDRUG-SM,ZENITH DRUGS,0,NaN,0.0,0.05,1600,EQ,NSE,NSE,ZENITHDRUG
82425,1827329,7138,ZODIAC-BE,ZODIAC ENERGY,0,NaN,0.0,0.05,1,EQ,NSE,NSE,ZODIAC

In [141]:
nse_df['primary'] = nse_df['tradingsymbol'].apply(lambda x: '-' in x)

/var/folders/d4/cgyr_gnj7nn2wy_hq40gkq8c0000gq/T/ipykernel_99828/3768278154.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nse_df['primary'] = nse_df['tradingsymbol'].apply(lambda x: '-' in x)

In [198]:
nse_df[nse_df.tradingsymbol == 'HDFCBANK']

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange,pre_split,primary,unique_primary_count,num_symbols
80193,341249,1333,HDFCBANK,HDFC BANK,0,NaN,0.0,0.05,1,EQ,NSE,NSE,HDFCBANK,False,2,2

In [178]:
nse_df[nse_df.instrument_token == 408065]

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange,pre_split,primary,unique_primary_count,num_symbols
80639,408065,1594,INFY,INFOSYS,0,NaN,0.0,0.05,1,EQ,NSE,NSE,INFY,False,1,1

In [144]:
nse_df['unique_primary_count'] = nse_df.groupby('pre_split')['primary'].transform('nunique')

/var/folders/d4/cgyr_gnj7nn2wy_hq40gkq8c0000gq/T/ipykernel_99828/2404683834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nse_df['unique_primary_count'] = nse_df.groupby('pre_split')['primary'].transform('nunique')

In [148]:
nse_df['num_symbols'] = nse_df.groupby('pre_split')['tradingsymbol'].transform('nunique')

/var/folders/d4/cgyr_gnj7nn2wy_hq40gkq8c0000gq/T/ipykernel_99828/4127190729.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nse_df['num_symbols'] = nse_df.groupby('pre_split')['tradingsymbol'].transform('nunique')

In [153]:
nse_df[(nse_df.unique_primary_count == 1) & (nse_df.num_symbols > 1)]['tradingsymbol'].values

array(['AAFS-N0', 'AAFS-N1', 'AAFS-N2', 'ABFL-N0', 'ABFL-N1', 'ABFL-N2',
       'ABFL-N3', 'ABFL-N4', 'ABFL-N5', 'ABFL-N6', 'ABFL-N7', 'ABFL-N8',
       'ABFL-N9', 'ABFL-NA', 'ABFL-NB', 'ABFL-NC', 'ABFL-ND', 'ABFL-NE',
       'ABHFL-N0', 'ABHFL-N1', 'ABHFL-N2', 'ABHFL-N3', 'ABHFL-N4',
       'ABHFL-N5', 'BCIPL-N0', 'BCIPL-N1', 'BCIPL-N2', 'CCSP-N0',
       'CCSP-N1', 'DHANILOANS-NF', 'DHANILOANS-NG', 'DHANILOANS-NH',
       'DHANILOANS-NO', 'DHANILOANS-NP', 'DHANILOANS-NQ', 'DHANILOANS-NV',
       'DHANILOANS-NW', 'DHANILOANS-NX', 'DHANILOANS-NZ', 'DHANILOANS-Y1',
       'DHANILOANS-Y2', 'DHANILOANS-Y3', 'DHANILOANS-Y4', 'DHANILOANS-Y5',
       'ECLFINANCE-NJ', 'ECLFINANCE-NK', 'ECLFINANCE-NR', 'ECLFINANCE-NS',
       'ERFLNCDI-N5', 'ERFLNCDI-N6', 'EXIM-N0', 'EXIM-N1', 'GODREJFIN-N0',
       'GODREJFIN-N1', 'HEFC-N0', 'HEFC-N1', 'IBUCCREDIT-NA',
       'IBUCCREDIT-NB', 'IBUCCREDIT-NC', 'IBUCCREDIT-ND', 'IBUCCREDIT-NE',
       'IBUCCREDIT-NF', 'IBUCCREDIT-NG', 'IBUCCREDIT-NH', 'IBUCCREDIT-NI',
       'IBUCCREDIT-NJ', 'IBUCCREDIT-NK', 'IBUCCREDIT-NL', 'IBUCCREDIT-NM',
       'IBUCCREDIT-NN', 'IBUCCREDIT-NO', 'IBUCCREDIT-NP', 'IBUCCREDIT-NQ',
       'IBUCCREDIT-NR', 'IBUCCREDIT-NS', 'IBUCCREDIT-NT', 'IBUCCREDIT-NU',
       'IBUCCREDIT-NV', 'IBUCCREDIT-NW', 'IBUCCREDIT-NX', 'IBUCCREDIT-NY',
       'IBUCCREDIT-NZ', 'IBULHSG-N1', 'IBULHSG-N2', 'IBULHSG-N3',
       'IBULHSG-N4', 'IBULHSG-N5', 'IBULHSG-N6', 'IBULHSG-N7',
       'IBULHSG-N8', 'IBULHSG-N9', 'IBULHSG-NA', 'IBULHSG-NB',
       'IBULHSG-NC', 'IBULHSG-ND', 'IBULHSG-NE', 'IBULHSG-NF',
       'IBULHSG-NG', 'IBULHSG-NH', 'IBULHSG-NI', 'IBULHSG-NJ',
       'IBULHSG-NK', 'IBULHSG-NL', 'IBULHSG-NM', 'IBULHSG-NN',
       'IBULHSG-NO', 'IBULHSG-NP', 'IBULHSG-NQ', 'IBULHSG-NR',
       'IBULHSG-NS', 'IBULHSG-NT', 'IBULHSG-NU', 'IBULHSG-NV',
       'IBULHSG-NW', 'IBULHSG-NX', 'IBULHSG-NY', 'IBULHSG-NZ',
       'IBULHSG-Y0', 'IBULHSG-Y1', 'IBULHSG-Y2', 'IBULHSG-Y3',
       'IBULHSG-Y4', 'IBULHSG-Y5', 'IBULHSG-Y6', 'IBULHSG-Y7',
       'IBULHSG-Y8', 'IBULHSG-Y9', 'IBULHSG-YA', 'IBULHSG-YB',
       'IBULHSG-YC', 'IBULHSG-YD', 'IBULHSG-YG', 'IBULHSG-YH',
       'IBULHSG-YI', 'IBULHSG-YJ', 'IBULHSG-YK', 'IBULHSG-YL',
       'IBULHSG-YM', 'IIFCL-N1', 'IIFCL-N3', 'IIFCL-N4', 'IIFLSAMFIN-N0',
       'IIFLSAMFIN-N1', 'IIFLSAMFIN-N2', 'IIFLSAMFIN-N3', 'IIFLSAMFIN-N4',
       'IIFLSAMFIN-N5', 'IIFLSAMFIN-N6', 'IIFLSAMFIN-N7', 'IIHFL-N4',
       'IIHFL-N5', 'IIHFL-N6', 'IIHFL-N7', 'IIHFL-N8', 'IIHFL-N9',
       'IIHFL-NA', 'IIHFL-NB', 'IIHFL-NC', 'IIHFL-ND', 'IIHFL-NE',
       'IMC1-N0', 'IMC1-N1', 'IMC1-N2', 'IMC1-N3', 'INCREDFIN-N4',
       'INCREDFIN-N5', 'INCREDFIN-N6', 'INCREDFIN-N7', 'INDIGRID-IV',
       'INDIGRID-NA', 'INDIGRID-NB', 'INDIGRID-NC', 'INDIGRID-ND',
       'INDIGRID-NE', 'INDIGRID-NF', 'INDIGRID-NG', 'INDIGRID-NH',
       'INDIGRID-NI', 'INDIGRID-NJ', 'INDIGRID-NK', 'INDIGRID-NL',
       'KISETSU-N0', 'KISETSU-N1', 'L&TFIN-N4', 'L&TFIN-N5', 'L&TFIN-N6',
       'L&TFIN-N7', 'L&TFIN-N8', 'L&TFIN-N9', 'L&TFIN-NA', 'L&TFIN-NB',
       'L&TFIN-NC', 'L&TFIN-ND', 'L&TFIN-NE', 'L&TFIN-NF', 'L&TFIN-NG',
       'L&TFIN-NH', 'L&TFIN-NI', 'L&TFIN-NJ', 'L&TFIN-NK', 'L&TFIN-NL',
       'L&TFIN-NM', 'L&TFIN-NN', 'L&TFIN-NO', 'L&TFIN-NP', 'L&TFIN-NQ',
       'NABARD-N0', 'NABARD-N1', 'NABARD-N2', 'NAVIFIN-N0', 'NAVIFIN-N3',
       'NAVIFIN-N4', 'NAVIFIN-N5', 'NAVIFIN-N6', 'NAVIFIN-N7',
       'NAVIFIN-N8', 'NAVIFIN-N9', 'NAVIFIN-NA', 'NAVIFIN-NB',
       'NAVIFIN-NC', 'NAVIFIN-ND', 'NHAI-N2', 'NHAI-N5', 'NHAI-N6',
       'NHAI-N7', 'NHAI-N8', 'NHAI-N9', 'NHAI-NA', 'NHAI-NB', 'NHAI-NC',
       'NHAI-ND', 'NHAI-NE', 'NHB-N8', 'NHB-N9', 'NHB-NA', 'NHBTF2014-N2',
       'NHBTF2014-N3', 'NHBTF2014-N5', 'NHBTF2014-N6', 'NHBTF2023-N3',
       'NHBTF2023-N4', 'NHBTF2023-N6', 'NHBTF2023-N7', 'NHIT-IV',
       'NHIT-N1', 'NHIT-N2', 'NHIT-N3', 'NIDO-N5', 'NIDO-N6', 'NIDO-N7',
       'NIIF-N0', 'NIIF-N1', 'NIIF-N2', 'NIRMA-N0', 'NIRMA-N6',
       'NIRMA-N7', 'NOMURA-N0', 'NOMURA-N1', 'PCHFL-N5', 'PCHFL-N6',
       'PCHFL-N7', 'PCHFL-N8', 'PCHFL-N9', 'PCHFL-NA', 'PCHFL-NB',
       'PCHFL-NC', 'SIDBI-N0', 'SIDBI-N1', 'SIDBI-N2', 'SMFG-N0',
       'SMFG-N1', 'SMFG-N2', 'SMFG-N3', 'TATACAP-N5', 'TATACAP-N6',
       'TATACAP-N7', 'TATACAP-N8', 'TATACAP-N9', 'TATACAP-NA',
       'TATACAP-NB', 'TATACAP-NC', 'TATACAP-ND', 'TATACAP-NE',
       'TATACAP-NF', 'TATACAPHSG-N3', 'TATACAPHSG-N4', 'TATACAPHSG-N5',
       'TATACAPHSG-N6', 'TATACAPHSG-N7', 'TATACAPHSG-N8', 'TATACAPHSG-N9',
       'TATACAPHSG-NA', 'TATACAPHSG-NB', 'TATACAPHSG-NC', 'TATACAPHSG-ND',
       'TFSI-N0', 'TFSI-N1', 'TFSI-N2', 'TPL-N0', 'TPL-N1', 'TPL-N2',
       'TPL-N3', 'TPL-N4', 'TPL-N5'], dtype=object)

In [143]:
nse_df.groupby('pre_split')['primary'].nunique()

pre_split
1018GS2026    1
182D010824    1
182D020524    1
182D040424    1
182D040724    1
             ..
ZOTA          1
ZUARI         1
ZUARIIND      1
ZYDUSLIFE     1
ZYDUSWELL     1
Name: primary, Length: 5575, dtype: int64

In [ ]:
nse_df

In [135]:
nse_df.groupby('pre_split')['tradingsymbol'].count().nlargest(75)

pre_split
IBULHSGFIN    122
IBULHSG        56
CHOLAFIN       30
IIFL           27
IBUCCREDIT     26
             ...
PNBHOUSING      2
RADIOCITY       2
SHAREINDIA      2
SUNDARMFIN      2
1018GS2026      1
Name: tradingsymbol, Length: 75, dtype: int64

In [116]:
len(set([x.split('-')[0] for x in nse_df['tradingsymbol']]))

5575

In [95]:
[x for x in nse_df.iterrows() if 'CUPID' in x['name']]

TypeError: tuple indices must be integers or slices, not str

In [105]:
nse_df.isnull().sum()

instrument_token       0
exchange_token         0
tradingsymbol          0
name                3683
last_price             0
expiry              6183
strike                 0
tick_size              0
lot_size               0
instrument_type        0
segment                0
exchange               0
dtype: int64

In [71]:
nse_equities = [f'NSE:{x}' for x in list(nse_df['tradingsymbol'])][4000:4600]

### Bulk OHLC

In [54]:
response.text

'<html>\r\n<head><title>414 Request-URI Too Large</title></head>\r\n<body>\r\n<center><h1>414 Request-URI Too Large</h1></center>\r\n</body>\r\n</html>\r\n'

In [180]:
from datetime import datetime, timedelta

In [181]:
timedelta(days=180)

datetime.timedelta(days=180)

In [187]:
(datetime.now() - timedelta(days=180)).strftime('%Y-%m-%d %H:%M:%S')

'2023-09-28 15:18:09'

In [176]:
import requests

url = "https://api.kite.trade/instruments/historical/408065/day"
headers = {
    "X-Kite-Version": "3",
    "Authorization": "token :"
}
params = {
    "from": '2024-01-01 00:00:00',
    "to": "2024-03-27 00:00:00"
}
s = time.time()
response = requests.get(url, headers=headers, params=params)
e = time.time()
data = response.json()

In [188]:
e-s

0.3076329231262207

In [189]:
pd.DataFrame(json.loads(response.text)['data']['candles'], columns = ['dt', 'open', 'high', 'low', 'close', 'volume'])

                          dt     open     high      low    close    volume
0   2024-01-01T00:00:00+0530  1539.00  1557.00  1535.25  1551.35   2808451
1   2024-01-02T00:00:00+0530  1546.00  1549.15  1523.00  1534.40   5396313
2   2024-01-03T00:00:00+0530  1519.95  1519.95  1488.00  1490.00   7550363
3   2024-01-04T00:00:00+0530  1504.95  1519.75  1492.90  1512.70   7056038
4   2024-01-05T00:00:00+0530  1506.75  1539.70  1506.25  1532.55   8895403
5   2024-01-08T00:00:00+0530  1528.95  1536.00  1513.25  1522.80   4440136
6   2024-01-09T00:00:00+0530  1541.90  1553.00  1525.85  1529.30   4412074
7   2024-01-10T00:00:00+0530  1524.95  1535.45  1505.00  1519.90   4096845
8   2024-01-11T00:00:00+0530  1524.90  1525.00  1486.60  1494.20  11296088
9   2024-01-12T00:00:00+0530  1562.00  1618.00  1555.40  1612.75  26754401
10  2024-01-15T00:00:00+0530  1644.95  1664.95  1636.00  1652.10  13228305
11  2024-01-16T00:00:00+0530  1644.80  1648.50  1625.00  1631.55   6500917
12  2024-01-17T00:00:00+0530  1620.25  1647.50  1620.25  1640.20   9209876
13  2024-01-18T00:00:00+0530  1642.65  1649.00  1628.25  1642.60   6375464
14  2024-01-19T00:00:00+0530  1651.60  1665.50  1644.15  1659.20   4522736
15  2024-01-20T00:00:00+0530  1665.55  1669.25  1645.00  1648.85   1158144
16  2024-01-23T00:00:00+0530  1650.10  1674.70  1637.70  1642.15   9401255
17  2024-01-24T00:00:00+0530  1659.90  1680.00  1645.00  1675.40   8999681
18  2024-01-25T00:00:00+0530  1672.95  1680.55  1658.00  1669.10   8865304
19  2024-01-29T00:00:00+0530  1665.15  1679.35  1647.60  1656.60   4253785
20  2024-01-30T00:00:00+0530  1662.45  1690.00  1648.25  1651.45   4995943
21  2024-01-31T00:00:00+0530  1648.25  1667.25  1638.10  1660.90   6763779
22  2024-02-01T00:00:00+0530  1659.55  1677.00  1650.35  1657.05   5760011
23  2024-02-02T00:00:00+0530  1666.05  1718.50  1665.00  1693.35   7858483
24  2024-02-05T00:00:00+0530  1694.75  1700.75  1681.85  1687.20   3634135
25  2024-02-06T00:00:00+0530  1686.75  1733.00  1673.95  1729.45   7694265
26  2024-02-07T00:00:00+0530  1729.00  1729.00  1686.85  1693.75   4613877
27  2024-02-08T00:00:00+0530  1698.00  1706.35  1682.80  1692.10   5919715
28  2024-02-09T00:00:00+0530  1684.70  1692.90  1659.80  1669.35   4600004
29  2024-02-12T00:00:00+0530  1670.35  1692.95  1670.35  1680.10   3555808
30  2024-02-13T00:00:00+0530  1683.00  1689.10  1663.50  1684.55   2696481
31  2024-02-14T00:00:00+0530  1660.20  1669.45  1635.50  1666.20   3768579
32  2024-02-15T00:00:00+0530  1677.00  1687.75  1661.60  1676.35   4834391
33  2024-02-16T00:00:00+0530  1689.00  1709.00  1687.95  1701.65   4880654
34  2024-02-19T00:00:00+0530  1705.00  1711.50  1687.70  1699.75   3690993
35  2024-02-20T00:00:00+0530  1685.00  1694.25  1668.75  1685.25   3706389
36  2024-02-21T00:00:00+0530  1674.00  1674.00  1645.30  1655.55   4300508
37  2024-02-22T00:00:00+0530  1665.00  1684.60  1644.40  1681.35   5841277
38  2024-02-23T00:00:00+0530  1697.00  1698.45  1671.90  1676.85   5373072
39  2024-02-26T00:00:00+0530  1674.95  1674.95  1645.00  1660.15   2782438
40  2024-02-27T00:00:00+0530  1661.00  1671.10  1652.80  1663.60   5159088
41  2024-02-28T00:00:00+0530  1670.00  1687.80  1662.05  1671.25   3188916
42  2024-02-29T00:00:00+0530  1665.00  1682.25  1653.30  1673.90   7814722
43  2024-03-01T00:00:00+0530  1669.00  1671.95  1651.00  1654.70   6387291
44  2024-03-02T00:00:00+0530  1658.85  1665.00  1654.05  1656.30    292153
45  2024-03-04T00:00:00+0530  1657.85  1664.45  1633.65  1637.20   4445156
46  2024-03-05T00:00:00+0530  1634.00  1637.35  1602.00  1606.50   4596579
47  2024-03-06T00:00:00+0530  1602.80  1620.15  1576.00  1617.55   6420684
48  2024-03-07T00:00:00+0530  1616.60  1628.45  1604.20  1616.45   6348359
49  2024-03-11T00:00:00+0530  1608.15  1613.80  1588.00  1600.60   6752895
50  2024-03-12T00:00:00+0530  1600.00  1625.00  1597.65  1612.95   4614222
51  2024-03-13T00:00:00+0530  1612.90  1624.50  1598.55  1611.40   5688997
52  2024-03-14T00:00:00+0530  1614.40  1657.75  1608.00  1653.30   8803799
53  2024-03-15T00:00:00+0530  1641.10  1645.80  1618.35  1634.00  11809997
54  2024-03-18T00:00:00+0530  1630.00  1632.65  1598.85  1602.65   4958904
55  2024-03-19T00:00:00+0530  1592.35  1599.00  1558.00  1561.45   6870411
56  2024-03-20T00:00:00+0530  1563.00  1574.95  1552.35  1554.95   4759059
57  2024-03-21T00:00:00+0530  1564.00  1576.95  1543.40  1554.70  11062497
58  2024-03-22T00:00:00+0530  1521.00  1528.90  1498.20  1508.85  14673890
59  2024-03-26T00:00:00+0530  1492.00  1507.45  1487.90  1493.45   6859448

In [84]:
e-s

0.2587890625

In [161]:
str(None)

'None'

In [85]:
len(data)

2

In [81]:
len(data['data'])

TypeError: object of type 'NoneType' has no len()

In [77]:
data['data']

{'NSE:HINDZINC': {'instrument_token': 364545,
  'last_price': 291.7,
  'ohlc': {'open': 294.95, 'high': 295.3, 'low': 290.8, 'close': 293.4}},
 'NSE:HIRECT': {'instrument_token': 3555841,
  'last_price': 580.6,
  'ohlc': {'open': 583, 'high': 609.95, 'low': 575.2, 'close': 587.7}},
 'NSE:HISARMETAL': {'instrument_token': 4946433,
  'last_price': 165.7,
  'ohlc': {'open': 164.8, 'high': 170.25, 'low': 164.8, 'close': 164.8}},
 'NSE:HITECH': {'instrument_token': 734209,
  'last_price': 118.25,
  'ohlc': {'open': 117.05, 'high': 120.35, 'low': 114.7, 'close': 116.3}},
 'NSE:HITECHCORP': {'instrument_token': 3881217,
  'last_price': 201.9,
  'ohlc': {'open': 209.9, 'high': 209.9, 'low': 201.2, 'close': 206.4}},
 'NSE:HITECHGEAR': {'instrument_token': 1134849,
  'last_price': 516.4,
  'ohlc': {'open': 531.5, 'high': 544.8, 'low': 508.65, 'close': 540.35}},
 'NSE:HLEGLAS': {'instrument_token': 585985,
  'last_price': 433,
  'ohlc': {'open': 442, 'high': 445.3, 'low': 430, 'close': 440.45}},
 'NSE:HLVLTD': {'instrument_token': 370689,
  'last_price': 21.75,
  'ohlc': {'open': 21.9, 'high': 22.8, 'low': 20.65, 'close': 21.4}},
 'NSE:HMAAGRO': {'instrument_token': 4365569,
  'last_price': 50.45,
  'ohlc': {'open': 52, 'high': 52, 'low': 49.45, 'close': 50.55}},
 'NSE:HMT-BZ': {'instrument_token': 5042689,
  'last_price': 42.8,
  'ohlc': {'open': 45.95, 'high': 46, 'low': 42.6, 'close': 44.8}},
 'NSE:HMVL': {'instrument_token': 4918017,
  'last_price': 87.95,
  'ohlc': {'open': 90.6, 'high': 91.8, 'low': 87.15, 'close': 90.6}},
 'NSE:HNDFDS': {'instrument_token': 3116289,
  'last_price': 482.7,
  'ohlc': {'open': 487.55, 'high': 487.55, 'low': 477.35, 'close': 485.05}},
 'NSE:HNGSNGBEES': {'instrument_token': 4680705,
  'last_price': 248.75,
  'ohlc': {'open': 249.88, 'high': 251.8, 'low': 248.01, 'close': 248.69}},
 'NSE:HOLMARC-SM': {'instrument_token': 4774145,
  'last_price': 88.5,
  'ohlc': {'open': 88.5, 'high': 88.5, 'low': 88.5, 'close': 92}},
 'NSE:HOMEFIRST': {'instrument_token': 526337,
  'last_price': 873.2,
  'ohlc': {'open': 851.35, 'high': 878, 'low': 850.55, 'close': 847.15}},
 'NSE:HOMESFY-SM': {'instrument_token': 3462657,
  'last_price': 466,
  'ohlc': {'open': 482.95, 'high': 483, 'low': 465.95, 'close': 452.5}},
 'NSE:HONASA': {'instrument_token': 5072129,
  'last_price': 368.9,
  'ohlc': {'open': 371.4, 'high': 372.15, 'low': 357.35, 'close': 367.95}},
 'NSE:HONAUT': {'instrument_token': 874753,
  'last_price': 37495.1,
  'ohlc': {'open': 37833.9, 'high': 38087.85, 'low': 37269, 'close': 38041.2}},
 'NSE:HONDAPOWER': {'instrument_token': 803329,
  'last_price': 2183.35,
  'ohlc': {'open': 2183.6, 'high': 2215.95, 'low': 2172.3, 'close': 2172.7}},
 'NSE:HOVS-BE': {'instrument_token': 3480321,
  'last_price': 56.95,
  'ohlc': {'open': 56.8, 'high': 58.9, 'low': 54, 'close': 56.1}},
 'NSE:HPAL': {'instrument_token': 1888257,
  'last_price': 95.25,
  'ohlc': {'open': 97.45, 'high': 97.8, 'low': 95, 'close': 96.5}},
 'NSE:HPIL-BE': {'instrument_token': 3020801,
  'last_price': 139.1,
  'ohlc': {'open': 140, 'high': 140, 'low': 132.9, 'close': 139.3}},
 'NSE:HPL': {'instrument_token': 4781825,
  'last_price': 294.55,
  'ohlc': {'open': 301.75, 'high': 303, 'low': 289.15, 'close': 298.4}},
 'NSE:HRHNEXT-SM': {'instrument_token': 5403393,
  'last_price': 30.25,
  'ohlc': {'open': 30.2, 'high': 30.7, 'low': 30.2, 'close': 31.65}},
 'NSE:HSCL-BE': {'instrument_token': 3670529,
  'last_price': 318.95,
  'ohlc': {'open': 321, 'high': 327, 'low': 305.05, 'close': 319.8}},
 'NSE:HTMEDIA': {'instrument_token': 3066625,
  'last_price': 24.5,
  'ohlc': {'open': 24.8, 'high': 24.9, 'low': 24.2, 'close': 24.65}},
 'NSE:HUBTOWN-BE': {'instrument_token': 3636993,
  'last_price': 116.15,
  'ohlc': {'open': 122, 'high': 125, 'low': 114.6, 'close': 120.6}},
 'NSE:HUDCO': {'instrument_token': 5331201,
  'last_price': 175.65,
  'ohlc': {'open': 179.6, 'high': 181.35, 'low': 170.8, 'close': 177.15}},
 'NSE:HUDCO-N2': {'instrument_token': 7997441,
  'last_price': 1089.52,
  'ohlc': {'open': 1090, 'high': 1090, 'low': 1085, 'close': 1085.15}},
 'NSE:HUDCO-N5': {'instrument_token': 7503873,
  'last_price': 1075.5,
  'ohlc': {'open': 1075.05, 'high': 1075.5, 'low': 1075.05, 'close': 1080}},
 'NSE:HUDCO-N7': {'instrument_token': 7590401,
  'last_price': 1060.1,
  'ohlc': {'open': 0, 'high': 1060.1, 'low': 1060.1, 'close': 1060.1}},
 'NSE:HUDCO-N8': {'instrument_token': 5101569,
  'last_price': 1125.1,
  'ohlc': {'open': 1126, 'high': 1126, 'low': 1125.1, 'close': 1144.5}},
 'NSE:HUDCO-N9': {'instrument_token': 5102081,
  'last_price': 1143.97,
  'ohlc': {'open': 1143.5, 'high': 1144, 'low': 1143.5, 'close': 1142}},
 'NSE:HUDCO-NB': {'instrument_token': 5110785,
  'last_price': 1159,
  'ohlc': {'open': 0, 'high': 1159, 'low': 1156, 'close': 1159}},
 'NSE:HUDCO-NC': {'instrument_token': 5111297,
  'last_price': 1367.3,
  'ohlc': {'open': 0, 'high': 1367.3, 'low': 1367.3, 'close': 1367.3}},
 'NSE:HUDCO-ND': {'instrument_token': 5111809,
  'last_price': 1163,
  'ohlc': {'open': 1164.05, 'high': 1164.4, 'low': 1163, 'close': 1164}},
 'NSE:HUDCO-NE': {'instrument_token': 5112321,
  'last_price': 1297,
  'ohlc': {'open': 1296.99, 'high': 1297, 'low': 1296, 'close': 1290}},
 'NSE:HUHTAMAKI': {'instrument_token': 655873,
  'last_price': 306.25,
  'ohlc': {'open': 304.4, 'high': 311, 'low': 303.05, 'close': 307.75}},
 'NSE:HYBRIDFIN-BE': {'instrument_token': 3280385,
  'last_price': 8.8,
  'ohlc': {'open': 8.8, 'high': 8.8, 'low': 8.4, 'close': 8.4}},
 'NSE:IBLFL-SM': {'instrument_token': 5465089,
  'last_price': 47.9,
  'ohlc': {'open': 48.6, 'high': 50.4, 'low': 47.65, 'close': 48.6}},
 'NSE:IBREALEST': {'instrument_token': 3699201,
  'last_price': 110.25,
  'ohlc': {'open': 110, 'high': 112.4, 'low': 107.5, 'close': 108.3}},
 'NSE:IBUCCREDIT-NA': {'instrument_token': 1261057,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBUCCREDIT-NB': {'instrument_token': 1262081,
  'last_price': 955,
  'ohlc': {'open': 0, 'high': 955, 'low': 954, 'close': 955}},
 'NSE:IBUCCREDIT-NC': {'instrument_token': 1263617,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBUCCREDIT-ND': {'instrument_token': 1265153,
  'last_price': 960,
  'ohlc': {'open': 0, 'high': 960, 'low': 960, 'close': 960}},
 'NSE:IBUCCREDIT-NE': {'instrument_token': 3585281,
  'last_price': 999.4,
  'ohlc': {'open': 0, 'high': 999.4, 'low': 988, 'close': 999.4}},
 'NSE:IBUCCREDIT-NF': {'instrument_token': 3586561,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBUCCREDIT-NG': {'instrument_token': 3588353,
  'last_price': 1072,
  'ohlc': {'open': 0, 'high': 1072, 'low': 1072, 'close': 1072}},
 'NSE:IBUCCREDIT-NH': {'instrument_token': 3589377,
  'last_price': 977,
  'ohlc': {'open': 977, 'high': 977, 'low': 977, 'close': 977.03}},
 'NSE:IBUCCREDIT-NI': {'instrument_token': 3590657,
  'last_price': 970,
  'ohlc': {'open': 0, 'high': 970, 'low': 970, 'close': 970}},
 'NSE:IBUCCREDIT-NJ': {'instrument_token': 3591169,
  'last_price': 1032,
  'ohlc': {'open': 0, 'high': 1032, 'low': 999, 'close': 1032}},
 'NSE:IBUCCREDIT-NK': {'instrument_token': 3591681,
  'last_price': 970,
  'ohlc': {'open': 0, 'high': 970, 'low': 970, 'close': 970}},
 'NSE:IBUCCREDIT-NL': {'instrument_token': 3592193,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBUCCREDIT-NM': {'instrument_token': 3592705,
  'last_price': 930,
  'ohlc': {'open': 930, 'high': 930, 'low': 930, 'close': 930}},
 'NSE:IBUCCREDIT-NN': {'instrument_token': 3593217,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBUCCREDIT-NO': {'instrument_token': 3593729,
  'last_price': 924.65,
  'ohlc': {'open': 949, 'high': 949, 'low': 900.3, 'close': 800}},
 'NSE:IBUCCREDIT-NP': {'instrument_token': 3892481,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBUCCREDIT-NQ': {'instrument_token': 3893761,
  'last_price': 1055,
  'ohlc': {'open': 0, 'high': 1055, 'low': 1055, 'close': 1055}},
 'NSE:IBUCCREDIT-NR': {'instrument_token': 3895041,
  'last_price': 950,
  'ohlc': {'open': 0, 'high': 950, 'low': 950, 'close': 950}},
 'NSE:IBUCCREDIT-NS': {'instrument_token': 3896321,
  'last_price': 1020.83,
  'ohlc': {'open': 0, 'high': 1020.83, 'low': 1020.83, 'close': 1020.83}},
 'NSE:IBUCCREDIT-NT': {'instrument_token': 3899137,
  'last_price': 1050.3,
  'ohlc': {'open': 0, 'high': 1050.3, 'low': 1050.3, 'close': 1050.3}},
 'NSE:IBUCCREDIT-NU': {'instrument_token': 3900161,
  'last_price': 950,
  'ohlc': {'open': 0, 'high': 950, 'low': 950, 'close': 950}},
 'NSE:IBUCCREDIT-NV': {'instrument_token': 3901441,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 591.75}},
 'NSE:IBUCCREDIT-NW': {'instrument_token': 3902721,
  'last_price': 1015,
  'ohlc': {'open': 0, 'high': 1015, 'low': 1015, 'close': 1015}},
 'NSE:IBUCCREDIT-NX': {'instrument_token': 3903745,
  'last_price': 1050.1,
  'ohlc': {'open': 1050.1, 'high': 1050.1, 'low': 1050.1, 'close': 1046.1}},
 'NSE:IBUCCREDIT-NY': {'instrument_token': 3904257,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 765}},
 'NSE:IBUCCREDIT-NZ': {'instrument_token': 3904769,
  'last_price': 975.2,
  'ohlc': {'open': 975.2, 'high': 975.2, 'low': 975.2, 'close': 1000}},
 'NSE:IBULHSG-N1': {'instrument_token': 4837633,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-N2': {'instrument_token': 4838913,
  'last_price': 1010,
  'ohlc': {'open': 1010, 'high': 1010, 'low': 1010, 'close': 1010}},
 'NSE:IBULHSG-N3': {'instrument_token': 4839425,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 0}},
 'NSE:IBULHSG-N4': {'instrument_token': 4839937,
  'last_price': 998,
  'ohlc': {'open': 0, 'high': 998.98, 'low': 998, 'close': 998}},
 'NSE:IBULHSG-N5': {'instrument_token': 5057537,
  'last_price': 973.97,
  'ohlc': {'open': 0, 'high': 973.97, 'low': 970, 'close': 973.97}},
 'NSE:IBULHSG-N6': {'instrument_token': 5058049,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-N7': {'instrument_token': 5058561,
  'last_price': 999.9,
  'ohlc': {'open': 999.9, 'high': 999.9, 'low': 999.9, 'close': 1017}},
 'NSE:IBULHSG-N8': {'instrument_token': 5059329,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-N9': {'instrument_token': 5060609,
  'last_price': 1000,
  'ohlc': {'open': 0, 'high': 1000, 'low': 1000, 'close': 1000}},
 'NSE:IBULHSG-NA': {'instrument_token': 5061121,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 9.63, 'low': 9.63, 'close': 1000}},
 'NSE:IBULHSG-NB': {'instrument_token': 5061633,
  'last_price': 990.01,
  'ohlc': {'open': 990.01, 'high': 990.01, 'low': 990.01, 'close': 990.01}},
 'NSE:IBULHSG-NC': {'instrument_token': 5062145,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 10}},
 'NSE:IBULHSG-ND': {'instrument_token': 5062657,
  'last_price': 980,
  'ohlc': {'open': 0, 'high': 980, 'low': 980, 'close': 980}},
 'NSE:IBULHSG-NE': {'instrument_token': 5105921,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-NF': {'instrument_token': 5107457,
  'last_price': 986.12,
  'ohlc': {'open': 0, 'high': 986.12, 'low': 986.12, 'close': 986.12}},
 'NSE:IBULHSG-NG': {'instrument_token': 5108993,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 0}},
 'NSE:IBULHSG-NH': {'instrument_token': 5118209,
  'last_price': 1003,
  'ohlc': {'open': 0, 'high': 1003, 'low': 1003, 'close': 1003}},
 'NSE:IBULHSG-NI': {'instrument_token': 5129473,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-NJ': {'instrument_token': 5129985,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-NK': {'instrument_token': 5131521,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-NL': {'instrument_token': 5135617,
  'last_price': 1000,
  'ohlc': {'open': 0, 'high': 1000, 'low': 1000, 'close': 1000}},
 'NSE:IBULHSG-NM': {'instrument_token': 5136641,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-NN': {'instrument_token': 5139201,
  'last_price': 1000,
  'ohlc': {'open': 0, 'high': 1000, 'low': 1000, 'close': 1000}},
 'NSE:IBULHSG-NO': {'instrument_token': 5140993,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-NP': {'instrument_token': 5142529,
  'last_price': 959,
  'ohlc': {'open': 0, 'high': 959, 'low': 959, 'close': 959}},
 'NSE:IBULHSG-NQ': {'instrument_token': 5144065,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-NR': {'instrument_token': 5146113,
  'last_price': 960,
  'ohlc': {'open': 0, 'high': 960, 'low': 798.92, 'close': 960}},
 'NSE:IBULHSG-NS': {'instrument_token': 5146625,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-NT': {'instrument_token': 5147137,
  'last_price': 937.2,
  'ohlc': {'open': 0, 'high': 937.2, 'low': 937.2, 'close': 937.2}},
 'NSE:IBULHSG-NU': {'instrument_token': 5148417,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-NV': {'instrument_token': 5149697,
  'last_price': 959,
  'ohlc': {'open': 0, 'high': 959, 'low': 959, 'close': 959}},
 'NSE:IBULHSG-NW': {'instrument_token': 5150209,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-NX': {'instrument_token': 5150721,
  'last_price': 910,
  'ohlc': {'open': 0, 'high': 910, 'low': 910, 'close': 910}},
 'NSE:IBULHSG-NY': {'instrument_token': 5152001,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-NZ': {'instrument_token': 5153281,
  'last_price': 1000,
  'ohlc': {'open': 0, 'high': 1000, 'low': 1000, 'close': 1000}},
 'NSE:IBULHSG-Y0': {'instrument_token': 5367809,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-Y1': {'instrument_token': 5368321,
  'last_price': 997,
  'ohlc': {'open': 0, 'high': 997, 'low': 995, 'close': 997}},
 'NSE:IBULHSG-Y2': {'instrument_token': 5368833,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-Y3': {'instrument_token': 5370113,
  'last_price': 975,
  'ohlc': {'open': 0, 'high': 975, 'low': 950.63, 'close': 975}},
 'NSE:IBULHSG-Y4': {'instrument_token': 5371393,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-Y5': {'instrument_token': 5371905,
  'last_price': 954.37,
  'ohlc': {'open': 925, 'high': 955, 'low': 921.21, 'close': 921.21}},
 'NSE:IBULHSG-Y6': {'instrument_token': 5372417,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-Y7': {'instrument_token': 5374721,
  'last_price': 955.41,
  'ohlc': {'open': 0, 'high': 955.41, 'low': 955.41, 'close': 955.41}},
 'NSE:IBULHSG-Y8': {'instrument_token': 5376001,
  'last_price': 962.95,
  'ohlc': {'open': 0, 'high': 962.95, 'low': 962.95, 'close': 962.95}},
 'NSE:IBULHSG-Y9': {'instrument_token': 5376769,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 0}},
 'NSE:IBULHSG-YA': {'instrument_token': 5378049,
  'last_price': 924.3,
  'ohlc': {'open': 0, 'high': 924.3, 'low': 924.3, 'close': 924.3}},
 'NSE:IBULHSG-YB': {'instrument_token': 5378561,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-YC': {'instrument_token': 5380097,
  'last_price': 990,
  'ohlc': {'open': 0, 'high': 990, 'low': 990, 'close': 990}},
 'NSE:IBULHSG-YD': {'instrument_token': 5380865,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-YG': {'instrument_token': 5382145,
  'last_price': 1000,
  'ohlc': {'open': 0, 'high': 1000, 'low': 1000, 'close': 1000}},
 'NSE:IBULHSG-YH': {'instrument_token': 5382657,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-YI': {'instrument_token': 5383169,
  'last_price': 990,
  'ohlc': {'open': 0, 'high': 990, 'low': 990, 'close': 990}},
 'NSE:IBULHSG-YJ': {'instrument_token': 5383681,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSG-YK': {'instrument_token': 5386753,
  'last_price': 984,
  'ohlc': {'open': 0, 'high': 984, 'low': 984, 'close': 984}},
 'NSE:IBULHSG-YL': {'instrument_token': 5387265,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 0}},
 'NSE:IBULHSG-YM': {'instrument_token': 5390337,
  'last_price': 848.07,
  'ohlc': {'open': 901.2, 'high': 901.2, 'low': 816.2, 'close': 990}},
 'NSE:IBULHSGFIN': {'instrument_token': 7712001,
  'last_price': 162.5,
  'ohlc': {'open': 164.65, 'high': 167.8, 'low': 162, 'close': 163.05}},
 'NSE:IBULHSGFIN-AA': {'instrument_token': 3756289,
  'last_price': 1140,
  'ohlc': {'open': 0, 'high': 1140, 'low': 800, 'close': 1140}},
 'NSE:IBULHSGFIN-AB': {'instrument_token': 3757569,
  'last_price': 1019,
  'ohlc': {'open': 0, 'high': 1019, 'low': 1019, 'close': 1019}},
 'NSE:IBULHSGFIN-AC': {'instrument_token': 3758849,
  'last_price': 950.2,
  'ohlc': {'open': 0, 'high': 970, 'low': 950.2, 'close': 950.2}},
 'NSE:IBULHSGFIN-AD': {'instrument_token': 3760129,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSGFIN-AG': {'instrument_token': 3761153,
  'last_price': 1055.68,
  'ohlc': {'open': 0, 'high': 1055.68, 'low': 1050.97, 'close': 1055.68}},
 'NSE:IBULHSGFIN-AH': {'instrument_token': 3768321,
  'last_price': 850,
  'ohlc': {'open': 0, 'high': 850, 'low': 850, 'close': 850}},
 'NSE:IBULHSGFIN-AI': {'instrument_token': 3768577,
  'last_price': 850,
  'ohlc': {'open': 850, 'high': 850, 'low': 850, 'close': 877}},
 'NSE:IBULHSGFIN-AJ': {'instrument_token': 3762177,
  'last_price': 1026.68,
  'ohlc': {'open': 1026.68, 'high': 1026.68, 'low': 1026.68, 'close': 1053}},
 'NSE:IBULHSGFIN-AK': {'instrument_token': 3764225,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSGFIN-AL': {'instrument_token': 3765761,
  'last_price': 905,
  'ohlc': {'open': 0, 'high': 925, 'low': 905, 'close': 905}},
 'NSE:IBULHSGFIN-AM': {'instrument_token': 3766785,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSGFIN-AN': {'instrument_token': 3767809,
  'last_price': 905,
  'ohlc': {'open': 0, 'high': 930, 'low': 899.7, 'close': 905}},
 'NSE:IBULHSGFIN-AO': {'instrument_token': 4474369,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSGFIN-AP': {'instrument_token': 4476161,
  'last_price': 988.93,
  'ohlc': {'open': 988.93, 'high': 988.93, 'low': 988.93, 'close': 1014.28}},
 'NSE:IBULHSGFIN-AQ': {'instrument_token': 4476929,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSGFIN-AR': {'instrument_token': 4480257,
  'last_price': 962.53,
  'ohlc': {'open': 0, 'high': 962.53, 'low': 962.53, 'close': 962.53}},
 'NSE:IBULHSGFIN-AS': {'instrument_token': 4480769,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 10}},
 'NSE:IBULHSGFIN-AT': {'instrument_token': 4481281,
  'last_price': 994.5,
  'ohlc': {'open': 994.5, 'high': 994.5, 'low': 994.5, 'close': 1020}},
 'NSE:IBULHSGFIN-AU': {'instrument_token': 4482049,
  'last_price': 0,
  'ohlc': {'open': 0, 'high': 0, 'low': 0, 'close': 1000}},
 'NSE:IBULHSGFIN-AV': {'instrument_token': 4483841,
  'last_price': 1021.4,
  'ohlc': {'open': 0, 'high': 1021.4, 'low': 993.17, 'close': 1021.4}},
 'NSE:IBULHSGFIN-AW': {'instrument_token': 4485377,
  'last_price': 850.1,
  'ohlc': {'open': 0, 'high': 850.1, 'low': 815.5, 'close': 850.1}},
 'NSE:IBULHSGFIN-AX': {'instrument_token': 4487169,
  'last_price': 1000,